version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  test-and-cov:
    executor:
      name: node/default
      tag: '16.13'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn run test
      - run: yarn run cov:send
workflows:
  test-app:
    jobs:
      - test-and-cov

